name: sol_book
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter:
    sdk: flutter
  persistent_bottom_nav_bar: ^5.0.2
  intl: ^0.19.0
  get_storage: ^2.1.1
  dio: ^5.4.0
  rflutter_alert: ^2.0.7

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/icons/
    - assets/data/
